travis:
  secure:
    BINSTAR_TOKEN: YF/ymDgtFL6grGjiverKa4xszKHG+B6oMVGjZmfoLctf1OGJikYzSTpROuKfkrA94I6iCwjJmSgBQbvuyLzYFmZfNv0CsQajD+IIRXs+Ghzw2F/jIMZqGjDR8DQsxAEeYjodPHdwJvWyCQ06sB3aH+I1apPtgGgQY2JN+LCseLZdYOMv1l0W/r3Q8zPM2R9pzK47ENWXY6iKW0aVw0sEr0cDejPpQOxLQNXiUNR3YSpzLS+QFxJQxWyeQYPKkbXyqLW58lXrCO/hmKdtfuZqUYysmMfNKPWefLvZMHVXlLGrn0d5+AygmN1clh1miwFvneNZDFuckYWHHpInlEmucXlg/Hki4DFoiDiKkJTZoXDo8k3GE9/VRj3Br1k+k0A1NVYjIyQfrb3eJpWK/ubG6wrBoAsG8ODy01XkejKViKgUmN9jN/YPLPOE2/0YlqOJkt8RpGfioel9BVsOovXFpr96WjddRTLHGfFXcyonmdnT9IttewMTNhIPL6y1EZ75r6qteJX57DqXam4sJQEafC7N6t+Smi1ASiLfzstaW8ZAVHcopSckpJmfBn2lr0WCGA7QPWqWoVWVqrodCHCC2xZtOPYo7jMr7Gnz3A3IfQFlQds/LsyO85z2fSMKqelS7YjeARfglmCMkhOJm8GSurkZIXFQan4EzUgwyXseIDE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
